version: '3'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_DB}"
      POSTGRES_USER: "${DATABASE_USER}"
      TZ: "Asia/Tokyo"
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      RAILS_ENV: "development"
      TZ: "Asia/Tokyo"
